# Generated by Django 5.0.6 on 2024-05-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('temp', models.FloatField(null=True, verbose_name='Temperature')),
                ('mlx_ambient_temp', models.FloatField(null=True, verbose_name='MLX Ambient Temperature')),
                ('ds_temp', models.FloatField(null=True, verbose_name='DS Temperature')),
                ('humidity', models.FloatField(null=True, verbose_name='Humidity')),
                ('heat_index', models.FloatField(null=True, verbose_name='Heat Index')),
                ('air_gases', models.FloatField(null=True, verbose_name='Air Gases')),
                ('pm1', models.IntegerField(null=True, verbose_name='PM1')),
                ('pm2_5', models.IntegerField(null=True, verbose_name='PM2.5')),
                ('pm10', models.IntegerField(null=True, verbose_name='PM10')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('skin_temperature', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
