# Generated by Django 5.0.6 on 2024-05-19 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
