# Generated by Django 5.0.6 on 2024-05-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp32_endpoint', '0003_alter_sensordata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='ds_temp',
        ),
    ]
