# Generated by Django 5.0.6 on 2024-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32_endpoint', '0004_remove_sensordata_ds_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsign',
            old_name='skin_temperature',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
