# Generated by Django 5.0.4 on 2024-05-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_birth_date_passwordchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordchangerequest',
            name='status',
        ),
    ]
