# Generated by Django 5.0.6 on 2024-05-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_email_address_user_phone_number_user_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
