# Generated by Django 5.0.6 on 2024-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='abdominal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='cardiac',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='chest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='extremities',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='other_findings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='present_illness_history',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctororder',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctororder',
            name='findings',
            field=models.CharField(default='Findings', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctororder',
            name='impression',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctororder',
            name='management',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
