# Generated by Django 5.0.6 on 2024-05-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_doctororder_abdominal_doctororder_cardiac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctororder',
            name='findings',
        ),
    ]
