# Generated by Django 5.0.6 on 2024-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_doctororder_findings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
