# Generated by Django 5.0.6 on 2024-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_vitalsigns_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
