# Generated by Django 5.0.6 on 2024-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_form_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursenotes',
            name='expected_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
