# Generated by Django 5.0.6 on 2024-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_nursenotes_expected_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('BRGY571', 'Barangay 571, Manila'), ('BRGY570', 'Barangay 570, Manila'), ('BRGY580', 'Barangay 580, Manila'), ('BRGY569', 'Barangay 569, Manila'), ('BRGY572', 'Barangay 572, Manila'), ('BRGY574', 'Barangay 574, Manila'), ('BRGY576', 'Barangay 576, Manila'), ('FRMMLA', 'From Manila'), ('OUTMLA', 'Outside Manila')], default='', max_length=10),
        ),
    ]
