# config.py

BASE_URL = 'http://192.168.50.18'

ENVIRONMENT_ENDPOINT = '/environment'
VITAL_SIGNS_ENDPOINT = '/vital-signs'

ENVIRONMENT_RESOURCE_URL = BASE_URL + ENVIRONMENT_ENDPOINT
VITAL_SIGNS_RESOURCE_URL = BASE_URL + VITAL_SIGNS_ENDPOINT